### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by olivier-stasse** [pal-robotics/pal_hardware_interfaces#1]
Dear all,
First thanks to make your code available, this is very valuable to the community.
Will it be possible to precise the license scheme you are using for this package ?
The license proprietary is a bit unprecise. We do not know for instance if a distribution scheme
based on this code should makes it available as it is right now or if it is limited to an internal usage.

As we would like to use it with partners in funded projects a clarification would be appreciated.
A BSD or LGPL license would have very much our preference...

**Comment by v-lopez** [comment]
Apologies for the delayed response, we were discussing this internally.

We'll use LGPL license for our published packages, we will update the packages in the coming days.

**Comment by olivier-stasse** [comment]
Many thanks to make the software available under this license !
